version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      # Install
      - run:
          name: Install Miniconda3
          command: ./install_miniconda.sh

      # Build
      - run:
          name: Build package
          command: |
            source ~/miniconda/bin/activate base
            conda build ./recipe

      # Upload
      - run:
          name: Upload packages
          command: |
            source ~/miniconda/bin/activate base
            ./upload_or_check_non_existence ./recipe sebp --channel=main
